# Generated by Django 4.1.6 on 2023-02-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='tech',
        ),
    ]
