# Generated by Django 3.2.18 on 2023-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.FilePathField(path='/img'),
        ),
        migrations.AlterField(
            model_name='position',
            name='img',
            field=models.FilePathField(path='/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FilePathField(path='/img'),
        ),
    ]
