# Generated by Django 4.1.6 on 2023-02-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='position',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='technology',
            new_name='tech',
        ),
    ]
