# Generated by Django 4.1.6 on 2023-02-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_rename_position_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('tech', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img', models.FilePathField(path='/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
